// <auto-generated />
namespace _5e_DM_ToolKit_v1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Dungeon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dungeon));
        
        string IMigrationMetadata.Id
        {
            get { return "201903110052199_Dungeon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
